serviceAccountName: ${service_account_name}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  hosts:
    - ${domain_name}

server:
  replicaCount: 1

  persistence:
    type: pvc
    enabled: true
    storageClassName: "${storage_class_name}"
    accessModes:
      - ReadWriteOnce
    size: 50Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/lifecycle
            operator: In
            values:
              - ondemand

